# Generated by Django 2.2.4 on 2019-08-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190823_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_be_returned', 'Set book as returned'),)},
        ),
    ]
